name: UdaCityShop - Package with Docker and SHA tag

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Docker meta
        id: meta-frontend
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/frontendservice
          tags: type=sha
      
      -
        name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: src/frontend/
          file: src/frontend/Dockerfile
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          
      
      -
        name: Docker meta
        id: meta-productcatalogservice
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/productcatalogservice
          tags: type=sha

      -
        name: Build and push productcatalogservice image
        uses: docker/build-push-action@v2
        with:
          context: src/productcatalogservice/
          file: src/productcatalogservice/Dockerfile
          push: true
          tags: ${{ steps.meta-productcatalogservice.outputs.tags }}
          

      -
        name: Docker meta
        id: meta-adservice
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/adservice
          tags: type=sha

      -
        name: Build and push adservice image
        uses: docker/build-push-action@v2
        with:
          context: src/adservice/
          file: src/adservice/Dockerfile
          push: true
          tags: ${{ steps.meta-adservice.outputs.tags }}

      -
        name: Docker meta
        id: meta-adservicev2
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/adservice-v2
          tags: type=sha

      -
        name: Build and push adservicev2 image
        uses: docker/build-push-action@v2
        with:
          context: src/adservice-v2/
          file: src/adservice-v2/Dockerfile
          push: true
          tags: ${{ steps.meta-adservicev2.outputs.tags }}
         
      -
        name: Docker meta
        id: meta-currencyservice
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/currencyservice
          tags: type=sha


      -
        name: Build and push currencyservice image
        uses: docker/build-push-action@v2
        with:
          context: src/currencyservice/
          file: src/currencyservice/Dockerfile
          push: true
          tags: ${{ steps.meta-currencyservice.outputs.tags }}
